name: Generate Commit Message

on: 
  push:
    branches:
      - main # Change to the name of your primary branch if it's not "main"

jobs:
  generate_message:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code.
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2 # This is important to fetch the previous commit as well

    # Step 2: Generate the new commit message.
    - name: Generate Commit Message
      id: generate_message
      run: echo "::set-output name=message::$(python .github/actions/generate_commit_msg.py)"
      
    # Step 3: Amend the commit with the new message.
    - name: Amend commit with new message
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
        git commit --amend -m "${{ steps.generate_message.outputs.message }}"
        git push --force-with-lease
