name: Code Review with OpenAI

on:
  push:
    branches:
      - main

jobs:
  review:
    name: Automated Code Review
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install openai PyGithub GitPython

    - name: Run review
      run: python .github/actions/code_review.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
